"""
Logiik Core Training Module.

Implements the Phase 7 teacher-student loop with iterative feedback
and the GenerativeCurriculum adapted from cognita/training/curriculum.py.

Key changes from legacy NERO/Cognita:
  - Phase 7 renamed from "Drosophila AI Framework" to
    "Niche Scientific Reasoning" with new question types.
  - Phase completion now combines plateau detection (existing)
    with coverage ratio + semantic saturation (new — CHUNK-08).
  - All logging routes through logiik/utils/logging.py.
  - All imports use logiik.* namespace.

Legacy reference:
  cognita/core/brain.py         → NEROBrain (unchanged, still used)
  cognita/training/curriculum.py → GenerativeCurriculum (migrated here)
"""
import uuid
import asyncio
import json
import math
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass

import torch
import numpy as np
from torch.optim import AdamW
from torch.optim.lr_scheduler import LinearLR
from torch.utils.data import DataLoader, Dataset

from logiik.curriculum.phases import PHASES, get_phase, PhaseConfig
from logiik.storage.text_store import TextStore
from logiik.embeddings.embed import get_embedder
from logiik.utils.logging import get_logger, log_event
from logiik.utils.helpers import validate_answer, compute_saturation

logger = get_logger("core.training")


# ─── Phase 7 data structures ──────────────────────────────────────────────────

@dataclass
class TeacherQuestion:
    """
    A single Phase 7 teacher-generated question with stepwise reasoning.
    Stored in Firebase via TextStore.
    """
    question_id: str
    prompt: str
    answer_steps: List[str]
    full_answer: str
    phase_id: int = 7
    difficulty: float = 0.94


@dataclass
class StudentAttempt:
    """
    A single student attempt at a Phase 7 question.
    May be updated through multiple feedback iterations.
    """
    question_id: str
    attempt_index: int
    student_answer_steps: List[str]
    student_full_answer: str
    feedback: Optional[List[str]] = None
    correctness: Optional[float] = None
    suggested_improvement: Optional[str] = None


# ─── Phase 7 Teacher-Student Loop ────────────────────────────────────────────

class Phase7TeacherStudentLoop:
    """
    Iterative teacher-student training loop for Phase 7:
    Niche Scientific Reasoning.

    Workflow per question:
      1. Teacher generates question + stepwise reasoning.
      2. Student generates stepwise answer + full answer.
      3. Teacher evaluates: assigns correctness score + feedback.
      4. If correctness < threshold (0.90): student regenerates.
      5. Loop until correctness >= 0.90 or max_iterations reached.
      6. Store final QA pair in Firebase + Pinecone.

    All questions and attempts persisted to Firebase via TextStore.
    """

    CORRECTNESS_THRESHOLD = 0.90
    MAX_ITERATIONS = 10    # Max feedback loops per question

    def __init__(self, text_store: Optional[TextStore] = None):
        self._store = text_store or TextStore()
        # In-memory stores (mirrored to Firebase)
        self._teacher_db: Dict[str, TeacherQuestion] = {}
        self._student_db: Dict[str, List[StudentAttempt]] = {}
        self._metrics: Dict[str, Dict] = {}
        logger.info("Phase7TeacherStudentLoop initialised.")

    def generate_teacher_question(
        self,
        prompt: str,
        answer_steps: List[str],
        full_answer: str,
        difficulty: float = 0.94
    ) -> str:
        """
        Register a teacher-generated question.

        In production, prompt + answer_steps are generated by the
        teacher model (GPT-4 / Claude API call). This method stores
        the result and returns the question_id.

        Args:
            prompt:       The scientific question/scenario.
            answer_steps: List of stepwise reasoning strings.
            full_answer:  Complete natural language answer.
            difficulty:   Difficulty score (0–1).

        Returns:
            question_id: UUID string.
        """
        qid = str(uuid.uuid4())
        question = TeacherQuestion(
            question_id=qid,
            prompt=prompt,
            answer_steps=answer_steps,
            full_answer=full_answer,
            difficulty=difficulty,
        )
        self._teacher_db[qid] = question
        self._student_db[qid] = []

        # Persist to Firebase
        self._store.store_phase7_teacher(qid, {
            "prompt": prompt,
            "answer_steps": answer_steps,
            "full_answer": full_answer,
            "difficulty": difficulty,
            "phase_id": 7,
        })

        logger.debug(f"Teacher question registered: id={qid}")
        return qid

    def student_attempt(
        self,
        question_id: str,
        student_answer_steps: List[str],
        student_full_answer: str
    ) -> StudentAttempt:
        """
        Record a student attempt at a Phase 7 question.

        Args:
            question_id:          ID from generate_teacher_question.
            student_answer_steps: Student's stepwise reasoning.
            student_full_answer:  Student's complete answer.

        Returns:
            StudentAttempt object (correctness not yet assigned).
        """
        if question_id not in self._student_db:
            self._student_db[question_id] = []

        attempt_index = len(self._student_db[question_id])
        attempt = StudentAttempt(
            question_id=question_id,
            attempt_index=attempt_index,
            student_answer_steps=student_answer_steps,
            student_full_answer=student_full_answer,
        )
        self._student_db[question_id].append(attempt)

        logger.debug(
            f"Student attempt recorded: "
            f"question_id={question_id}, attempt={attempt_index}"
        )
        return attempt

    def provide_feedback(
        self,
        question_id: str,
        attempt_index: int,
        feedback: List[str],
        correctness: float,
        suggested_improvement: Optional[str] = None
    ) -> bool:
        """
        Apply teacher feedback to a student attempt.

        Args:
            question_id:            Target question ID.
            attempt_index:          Index of the attempt to update.
            feedback:               List of feedback strings per step.
            correctness:            Score 0–1 (threshold: 0.90).
            suggested_improvement:  Optional specific improvement hint.

        Returns:
            True if correctness threshold met (phase 7 QA accepted).
            False if student should regenerate.
        """
        if question_id not in self._student_db:
            logger.error(f"provide_feedback: unknown question_id={question_id}")
            return False

        attempts = self._student_db[question_id]
        if attempt_index >= len(attempts):
            logger.error(
                f"provide_feedback: attempt_index={attempt_index} "
                f"out of range for question_id={question_id}"
            )
            return False

        attempt = attempts[attempt_index]
        attempt.feedback = feedback
        attempt.correctness = correctness
        attempt.suggested_improvement = suggested_improvement

        # Persist feedback to Firebase
        self._store.store_phase7_student(
            f"{question_id}_attempt_{attempt_index}",
            {
                "question_id": question_id,
                "attempt_index": attempt_index,
                "student_answer_steps": attempt.student_answer_steps,
                "student_full_answer": attempt.student_full_answer,
                "feedback": feedback,
                "correctness": correctness,
                "suggested_improvement": suggested_improvement or "",
            }
        )

        threshold_met = correctness >= self.CORRECTNESS_THRESHOLD
        status = "ACCEPTED" if threshold_met else "NEEDS_REVISION"
        logger.info(
            f"Feedback applied: question_id={question_id}, "
            f"attempt={attempt_index}, correctness={correctness:.2f}, "
            f"status={status}"
        )
        return threshold_met

    def run_feedback_loop(
        self,
        question_id: str,
        student_fn,
        teacher_fn
    ) -> Tuple[bool, int, float]:
        """
        Run the full iterative feedback loop for one question.

        Args:
            question_id: Target question ID.
            student_fn:  Callable(prompt, steps, suggestion) ->
                         (answer_steps: List[str], full_answer: str)
            teacher_fn:  Callable(prompt, teacher_steps,
                         student_steps, student_answer) ->
                         (feedback: List[str], correctness: float,
                          suggestion: str)

        Returns:
            Tuple of (threshold_met: bool, iterations: int,
                      final_correctness: float)
        """
        if question_id not in self._teacher_db:
            logger.error(
                f"run_feedback_loop: unknown question_id={question_id}"
            )
            return False, 0, 0.0

        question = self._teacher_db[question_id]
        threshold_met = False
        final_correctness = 0.0
        suggestion = None

        for iteration in range(self.MAX_ITERATIONS):
            # Student generates answer
            student_steps, student_answer = student_fn(
                question.prompt,
                question.answer_steps,
                suggestion
            )

            # Validate minimum answer quality
            if not validate_answer(student_answer):
                logger.warning(
                    f"Student answer failed validation at iteration "
                    f"{iteration} for question_id={question_id}"
                )
                continue

            # Record attempt
            self.student_attempt(question_id, student_steps, student_answer)

            # Teacher evaluates
            feedback, correctness, suggestion = teacher_fn(
                question.prompt,
                question.answer_steps,
                student_steps,
                student_answer
            )

            # Apply feedback
            threshold_met = self.provide_feedback(
                question_id,
                iteration,
                feedback,
                correctness,
                suggestion
            )
            final_correctness = correctness

            if threshold_met:
                logger.info(
                    f"Phase 7 question accepted after {iteration + 1} "
                    f"iterations: correctness={correctness:.2f}"
                )
                break
            else:
                logger.debug(
                    f"Iteration {iteration + 1}: correctness={correctness:.2f} "
                    f"< {self.CORRECTNESS_THRESHOLD} — regenerating."
                )

        if not threshold_met:
            logger.warning(
                f"Phase 7 question {question_id} did not meet threshold "
                f"after {self.MAX_ITERATIONS} iterations. "
                f"Final correctness={final_correctness:.2f}"
            )

        # Record metrics
        self._metrics[question_id] = {
            "iterations": min(self.MAX_ITERATIONS, iteration + 1),
            "final_correctness": final_correctness,
            "threshold_met": threshold_met,
        }

        return threshold_met, iteration + 1, final_correctness

    def get_metrics(self) -> Dict:
        """Return aggregate Phase 7 loop metrics."""
        if not self._metrics:
            return {"total_questions": 0}
        total = len(self._metrics)
        accepted = sum(1 for m in self._metrics.values() if m["threshold_met"])
        avg_iter = np.mean([m["iterations"] for m in self._metrics.values()])
        avg_corr = np.mean(
            [m["final_correctness"] for m in self._metrics.values()]
        )
        return {
            "total_questions": total,
            "accepted": accepted,
            "acceptance_rate": accepted / total,
            "avg_iterations": float(avg_iter),
            "avg_final_correctness": float(avg_corr),
        }


# ─── Processed example for DataLoader ────────────────────────────────────────

@dataclass
class ProcessedExample:
    """Tokenized training example for DataLoader."""
    input_ids: torch.Tensor
    attention_mask: torch.Tensor
    labels: torch.Tensor
    teacher_logits: Optional[torch.Tensor]
    weight: float


def collate_examples(batch: List[ProcessedExample]) -> ProcessedExample:
    """
    Custom collate — stacks fixed-size tensors.
    Drops variable-length teacher_logits to avoid shape mismatch.
    Preserved from legacy cognita/training/curriculum.py.
    """
    return ProcessedExample(
        input_ids=torch.stack([b.input_ids for b in batch]),
        attention_mask=torch.stack([b.attention_mask for b in batch]),
        labels=torch.stack([b.labels for b in batch]),
        teacher_logits=None,
        weight=sum(b.weight for b in batch) / len(batch),
    )


# ─── Training example type ────────────────────────────────────────────────────

@dataclass
class TrainingExample:
    """
    Single training example in Logiik Q+A format.
    Migrated from cognita/core/teacher_interface.py TrainingExample.
    """
    question: str
    answers: List[str]
    correct_indices: List[int]
    difficulty: float
    domain: str
    explanation: str


# ─── Curriculum Dataset ───────────────────────────────────────────────────────

class CurriculumDataset(Dataset):
    """
    Dataset implementing the Q+A training structure.
    Migrated and renamed from legacy CurriculumDataset.
    Preserves all logic including train/val split and
    soft teacher logit simulation.
    """

    def __init__(
        self,
        examples: List[TrainingExample],
        tokenizer,
        max_length: int = 512,
        generative_ratio: float = 0.3,
        val_ratio: float = 0.1,
        _items=None,
    ):
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.generative_ratio = generative_ratio

        if _items is not None:
            self.items = _items
            self.examples = examples
            self._val_dataset = None
            return

        all_items = [
            (ex, ans_idx)
            for ex in examples
            for ans_idx in range(len(ex.answers))
        ]
        split = int(len(all_items) * (1 - val_ratio))
        self.items = all_items[:split]
        val_items = all_items[split:]
        self._val_dataset = CurriculumDataset(
            examples, tokenizer, max_length,
            generative_ratio, _items=val_items
        )
        self.examples = examples

    @property
    def val_dataset(self):
        return self._val_dataset

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx) -> ProcessedExample:
        example, ans_idx = self.items[idx]
        question_prefix = f"Question: {example.question}\nAnswer:"
        formatted_text = (
            f"Question: {example.question}\n"
            f"Answer: {example.answers[ans_idx]}"
        )
        encoding = self.tokenizer(
            formatted_text,
            max_length=self.max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt"
        )
        prefix_ids = self.tokenizer(
            question_prefix,
            add_special_tokens=False,
            return_tensors="pt"
        )["input_ids"]
        prefix_len = prefix_ids.shape[1]
        labels = encoding["input_ids"].clone()
        labels[labels == self.tokenizer.pad_token_id] = -100
        labels[:, :prefix_len] = -100

        teacher_logits = self._simulate_teacher_logits(example, ans_idx)
        weight = 1.0 + example.difficulty

        return ProcessedExample(
            input_ids=encoding["input_ids"].squeeze(0),
            attention_mask=encoding["attention_mask"].squeeze(0),
            labels=labels.squeeze(0),
            teacher_logits=teacher_logits,
            weight=weight
        )

    def _simulate_teacher_logits(
        self, example: TrainingExample, ans_idx: int
    ) -> torch.Tensor:
        vocab_size = self.tokenizer.vocab_size
        answer_tokens = self.tokenizer.encode(
            example.answers[ans_idx], add_special_tokens=False
        )
        seq_len = len(answer_tokens)
        logits = torch.zeros(seq_len, vocab_size)
        for pos, token_id in enumerate(answer_tokens):
            if token_id < vocab_size:
                logits[pos, token_id] = 2.0
        return logits


# ─── Generative Curriculum ────────────────────────────────────────────────────

class GenerativeCurriculum:
    """
    Logiik curriculum engine.
    Migrated from cognita/training/curriculum.py GenerativeCurriculum.

    Phase 7 updated: "Drosophila AI Framework" replaced with
    "Niche Scientific Reasoning" (teacher_student=True,
    correctness_threshold=0.90).

    Phase advancement uses plateau detection from server.py
    (val_loss plateau) combined with coverage + saturation
    metrics added in CHUNK-08.
    """

    def __init__(
        self,
        teacher_orchestrator,
        tokenizer,
        topics_description: str = "",
        phase_ratios: Tuple[float, ...] = (
            0.10, 0.50, 0.65, 0.70, 0.88,
            0.93, 0.93, 0.92, 0.90, 0.94,
            0.95, 0.95
        ),
        phase_topics: Optional[Dict[str, List[str]]] = None,
        topics_per_session: int = 5,
    ):
        self.teacher = teacher_orchestrator
        self.tokenizer = tokenizer
        self.topics_description = topics_description
        self.topics_per_session = topics_per_session
        self.current_phase = 0   # 0-indexed internally

        # Phase names from canonical PHASES list
        self.phase_names = [p.display_name for p in PHASES]
        self.phase_configs = {p.display_name: p for p in PHASES}

        self.phase_ratios = self._normalize_ratios(phase_ratios)
        self.phase_topics: Dict[str, List[str]] = phase_topics or {}
        self._topic_cursors: Dict[str, int] = {
            name.lower(): 0 for name in self.phase_names
        }

        # Phase 6 teacher-student loop instance
        # (Niche Scientific Reasoning — was Phase 7)
        self._phase6_loop = Phase7TeacherStudentLoop()
        # Phase 11 uses same loop mechanism
        self._phase11_loop = Phase7TeacherStudentLoop()

        logger.info(
            f"GenerativeCurriculum initialised: "
            f"{len(self.phase_names)} phases"
        )

    def _normalize_ratios(
        self, ratios: Tuple[float, ...]
    ) -> Tuple[float, ...]:
        n = len(self.phase_names)
        if not ratios:
            return tuple(0.3 for _ in range(n))
        if len(ratios) < n:
            pad = ratios[-1]
            return tuple(ratios) + tuple(pad for _ in range(n - len(ratios)))
        return tuple(ratios[:n])

    def _get_topics(self) -> List[str]:
        phase_key = self.phase_names[self.current_phase].lower()
        topics = self.phase_topics.get(phase_key, [])
        if not topics:
            return (
                [self.topics_description]
                if self.topics_description.strip()
                else ["general_knowledge"]
            )
        n = len(topics)
        start = self._topic_cursors[phase_key]
        selected = [
            topics[(start + i) % n]
            for i in range(self.topics_per_session)
        ]
        self._topic_cursors[phase_key] = (
            (start + self.topics_per_session) % n
        )
        return selected

    def generate_phase_batch(
        self,
        batch_size: int,
        question_bank=None,
    ) -> CurriculumDataset:
        """Generate training batch for current phase."""
        phase_name = self.phase_names[self.current_phase]
        phase_config = self.phase_configs[phase_name]

        logger.info(
            f"Generating batch: phase={phase_name}, "
            f"batch_size={batch_size}"
        )

        # Route to phase-specific generator
        if self.current_phase == 0:
            # Phase 1 — Memorization
            examples = self._gen_memorization(batch_size)
        elif self.current_phase == 1:
            # Phase 2 — Generation
            examples = self._gen_generation(batch_size)
        elif self.current_phase == 2:
            # Phase 3 — Scientific Language & Literature
            examples = self._gen_scientific_language(batch_size)
        elif self.current_phase == 3:
            # Phase 4 — Mathematical & Statistical Reasoning
            examples = self._gen_mathematical_statistical(batch_size)
        elif self.current_phase == 4:
            # Phase 5 — Scientific Reasoning & Experimental Design
            examples = self._gen_scientific_reasoning(batch_size)
        elif self.current_phase == 5:
            # Phase 6 — Niche & Interdisciplinary Scientific Reasoning
            examples = self._gen_niche_scientific(batch_size)
        elif self.current_phase == 6:
            # Phase 7 — Scientific Image & Data Analysis
            examples = self._gen_image_data_analysis(batch_size)
        elif self.current_phase == 7:
            # Phase 8 — Research Computing & Scientific Coding
            examples = self._gen_research_computing(batch_size)
        elif self.current_phase == 8:
            # Phase 9 — Engineering Execution & Reliability
            examples = self._gen_engineering(batch_size)
        elif self.current_phase == 9:
            # Phase 10 — Abstraction & Cross-Domain Synthesis
            examples = self._gen_abstraction(batch_size)
        elif self.current_phase == 10:
            # Phase 11 — Adversarial Robustness & Epistemic Integrity
            examples = self._gen_adversarial_robustness(batch_size)
        elif self.current_phase == 11:
            # Phase 12 — Synthetic Judgment
            examples = self._gen_synthetic_judgment(batch_size)
        else:
            examples = self._gen_memorization(batch_size)

        # Deduplication via question bank
        if question_bank and examples:
            filtered = [
                ex for ex in examples
                if question_bank.check_and_log(
                    ex.question, self.topics_description
                )
            ]
            examples = filtered if filtered else examples[:1]

        return CurriculumDataset(
            examples,
            self.tokenizer,
            generative_ratio=self.phase_ratios[self.current_phase]
        )

    def advance_phase(self) -> bool:
        """Advance to next phase. Returns False if already at last phase."""
        if self.current_phase < len(self.phase_names) - 1:
            self.current_phase += 1
            logger.info(
                f"Advanced to phase {self.current_phase + 1}: "
                f"{self.phase_names[self.current_phase]}"
            )
            return True
        logger.info("All phases complete.")
        return False

    # ─── Phase generators ─────────────────────────────────────────────────

    def _make_example(
        self,
        topic: str,
        prefix: str,
        suffix: str,
        difficulty: float,
        domain_prefix: str,
    ) -> TrainingExample:
        """Helper: generate one example via teacher, apply prefix/suffix."""
        base = self.teacher.teachers[0].generate_training_example(
            topic, difficulty=difficulty, num_answers=5
        )
        return TrainingExample(
            question=f"{prefix}{base.question}\n{suffix}",
            answers=base.answers,
            correct_indices=base.correct_indices,
            difficulty=difficulty,
            domain=f"{domain_prefix}_{base.domain}",
            explanation=base.explanation,
        )

    def _gen_memorization(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        return self.teacher.generate_curriculum_batch(
            topics,
            examples_per_topic=max(1, count // len(topics)),
            difficulty_progression=True
        )

    def _gen_generation(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        examples = []
        for topic in topics:
            base = self.teacher.teachers[0].generate_training_example(
                topic, num_answers=3
            )
            examples.append(TrainingExample(
                question=(
                    base.question +
                    "\n(Provide an original answer based on "
                    "your understanding)"
                ),
                answers=["[GENERATE]"],
                correct_indices=[0],
                difficulty=min(base.difficulty * 1.2, 1.0),
                domain=base.domain,
                explanation="Generate original answer showing understanding",
            ))
        return examples[:count]

    def _gen_abstraction(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        return [
            self._make_example(
                topics[i % len(topics)],
                prefix="Connecting ideas across fields: ",
                suffix="(Draw on knowledge from multiple domains)",
                difficulty=0.90,
                domain_prefix="cross_domain",
            )
            for i in range(count)
        ]

    def _gen_engineering(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        return [
            self._make_example(
                topics[i % len(topics)],
                prefix="Engineering execution scenario: ",
                suffix=(
                    "(Plan implementation, propose tests, debug likely "
                    "failure modes, and justify trade-offs in "
                    "reliability/security/performance)"
                ),
                difficulty=0.92,
                domain_prefix="engineering_execution",
            )
            for i in range(count)
        ]

    def _gen_coding(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        return [
            self._make_example(
                topics[i % len(topics)],
                prefix="Coding mastery challenge: ",
                suffix=(
                    "(Demonstrate robust implementation choices across "
                    "common programming languages)"
                ),
                difficulty=0.95,
                domain_prefix="coding_mastery",
            )
            for i in range(count)
        ]

    def _gen_scientific_reasoning(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        return [
            self._make_example(
                topics[i % len(topics)],
                prefix="Scientific reasoning challenge: ",
                suffix=(
                    "(State hypotheses, define controls, identify "
                    "confounders, and provide uncertainty-aware conclusions)"
                ),
                difficulty=0.96,
                domain_prefix="scientific_reasoning",
            )
            for i in range(count)
        ]

    def _gen_niche_scientific(self, count: int) -> List[TrainingExample]:
        """
        Phase 7: Niche Scientific Reasoning.
        Generates interdisciplinary, mechanistic, and hypothetical
        scientific prompts requiring stepwise reasoning.

        NOTE: In full Phase 7 operation, these examples feed into
        Phase7TeacherStudentLoop.run_feedback_loop() for iterative
        correctness enforcement. The CurriculumDataset returned here
        is used for the base training pass; the feedback loop runs
        as a separate process via the API.
        """
        topics = self._get_topics()
        question_types = [
            "hypothetical_scenario",
            "multi_step_experimental_design",
            "interdisciplinary_synthesis",
            "mechanistic_reasoning",
            "rare_data_interpretation",
        ]
        examples = []
        for i in range(count):
            topic = topics[i % len(topics)]
            q_type = question_types[i % len(question_types)]
            base = self.teacher.teachers[0].generate_training_example(
                topic, difficulty=0.95, num_answers=5
            )
            examples.append(TrainingExample(
                question=(
                    f"[{q_type.replace('_', ' ').title()}] "
                    f"{base.question}\n"
                    "(Provide stepwise reasoning: identify mechanism, "
                    "predict outcome, explain experimental evidence, "
                    "address edge cases and interdisciplinary connections.)"
                ),
                answers=base.answers,
                correct_indices=base.correct_indices,
                difficulty=0.98,
                domain=f"niche_scientific_{base.domain}",
                explanation=(
                    f"Niche scientific reasoning [{q_type}]: "
                    f"{base.explanation}"
                ),
            ))
        return examples

    def _gen_scientific_language(
        self, count: int
    ) -> List[TrainingExample]:
        """
        Phase 3: Scientific Language & Literature.
        Generates prompts requiring parsing, classification,
        and production of scientific writing conventions.
        """
        topics = self._get_topics()
        question_type_suffixes = [
            (
                "Classify each sentence in the following passage "
                "as one of: [established_fact | experimental_result "
                "| hypothesis | speculation | methodological_claim]. "
                "Justify each classification."
            ),
            (
                "Identify all hedging language in the following "
                "abstract excerpt. For each hedge, explain what "
                "claim is being softened and why."
            ),
            (
                "Restate the following methods section in plain "
                "language without losing scientific precision. "
                "Identify any ambiguities present in the original."
            ),
            (
                "Distinguish which statements in the following "
                "results section are direct observations vs. "
                "inferences. Identify any unsupported leaps."
            ),
            (
                "Rewrite the following sentence at publication "
                "register: precise, hedged where appropriate, "
                "and without overclaiming."
            ),
        ]
        examples = []
        for i in range(count):
            topic = topics[i % len(topics)]
            suffix = question_type_suffixes[i % len(question_type_suffixes)]
            base = self.teacher.teachers[0].generate_training_example(
                topic, difficulty=0.80, num_answers=5
            )
            examples.append(TrainingExample(
                question=(
                    f"[Scientific Language Task]\n"
                    f"Topic: {topic}\n"
                    f"Context: {base.question}\n\n"
                    f"{suffix}"
                ),
                answers=base.answers,
                correct_indices=base.correct_indices,
                difficulty=0.80,
                domain=f"scientific_language_{base.domain}",
                explanation=(
                    f"Scientific language and literature task: "
                    f"{base.explanation}"
                ),
            ))
        return examples

    def _gen_mathematical_statistical(
        self, count: int
    ) -> List[TrainingExample]:
        """
        Phase 4: Mathematical & Statistical Reasoning.
        Generates prompts requiring quantitative evaluation
        of scientific evidence and statistical outputs.
        """
        topics = self._get_topics()
        question_type_suffixes = [
            (
                "Interpret the following statistical output. "
                "State what can and cannot be concluded. "
                "Identify any errors in the authors' interpretation."
            ),
            (
                "Evaluate this experimental design for statistical "
                "validity. Identify: sample size adequacy, "
                "multiple comparisons issues, confounders, "
                "and appropriate statistical test selection."
            ),
            (
                "The following data visualisation is described. "
                "State what it shows, what it does not show, "
                "and what single change would most improve it."
            ),
            (
                "Apply Bayesian reasoning to update the following "
                "prior belief given the new evidence. Show your "
                "reasoning explicitly."
            ),
            (
                "Propagate uncertainty through the following "
                "multi-step calculation. State the dominant "
                "source of error and whether the final precision "
                "is justified."
            ),
            (
                "Evaluate whether the reported effect size is "
                "scientifically meaningful given the domain context, "
                "independent of statistical significance."
            ),
        ]
        examples = []
        for i in range(count):
            topic = topics[i % len(topics)]
            suffix = question_type_suffixes[i % len(question_type_suffixes)]
            base = self.teacher.teachers[0].generate_training_example(
                topic, difficulty=0.85, num_answers=5
            )
            examples.append(TrainingExample(
                question=(
                    f"[Mathematical & Statistical Reasoning Task]\n"
                    f"Topic: {topic}\n"
                    f"Context: {base.question}\n\n"
                    f"{suffix}"
                ),
                answers=base.answers,
                correct_indices=base.correct_indices,
                difficulty=0.85,
                domain=f"mathematical_statistical_{base.domain}",
                explanation=(
                    f"Mathematical and statistical reasoning: "
                    f"{base.explanation}"
                ),
            ))
        return examples

    def _gen_image_data_analysis(
        self, count: int
    ) -> List[TrainingExample]:
        """
        Phase 7: Scientific Image & Data Analysis.
        Generates prompts requiring figure interpretation,
        limitation analysis, and follow-up experiment design.
        """
        topics = self._get_topics()
        question_type_suffixes = [
            (
                "A scientific figure is described below. "
                "State: (1) what the figure shows, "
                "(2) what it does NOT show, "
                "(3) what single follow-up experiment it suggests."
            ),
            (
                "Interpret the following experimental data table. "
                "Identify the key result, any anomalous entries, "
                "and what statistical test should be applied."
            ),
            (
                "The following microscopy image description is given. "
                "Classify what is visible, assess image quality "
                "indicators, and state what controls would be needed "
                "to support the authors' interpretation."
            ),
            (
                "Critically analyse this plot. State what the axes "
                "represent, whether the scale is appropriate, "
                "whether error bars are present and correct, "
                "and what the data actually supports."
            ),
        ]
        examples = []
        for i in range(count):
            topic = topics[i % len(topics)]
            suffix = question_type_suffixes[i % len(question_type_suffixes)]
            base = self.teacher.teachers[0].generate_training_example(
                topic, difficulty=0.88, num_answers=5
            )
            examples.append(TrainingExample(
                question=(
                    f"[Scientific Image & Data Analysis Task]\n"
                    f"Topic: {topic}\n"
                    f"Context: {base.question}\n\n"
                    f"{suffix}"
                ),
                answers=base.answers,
                correct_indices=base.correct_indices,
                difficulty=0.88,
                domain=f"image_data_analysis_{base.domain}",
                explanation=(
                    f"Scientific image and data analysis: "
                    f"{base.explanation}"
                ),
            ))
        return examples

    def _gen_research_computing(
        self, count: int
    ) -> List[TrainingExample]:
        """
        Phase 8: Research Computing & Scientific Coding.
        Generates prompts requiring domain-grounded scientific
        programming tasks. NOT generic coding — every task
        is in a research context.
        """
        topics = self._get_topics()
        question_type_suffixes = [
            (
                "Write Python code to process the following "
                "experimental dataset. Include: artifact detection, "
                "per-group statistics, an appropriate statistical "
                "test, and a publication-ready results summary "
                "with effect size and confidence interval."
            ),
            (
                "Implement the following numerical method in Python. "
                "Address: numerical stability, convergence criteria, "
                "and include a validation test against a known "
                "analytical solution."
            ),
            (
                "The following scientific analysis pipeline has a bug "
                "that produces a plausible but incorrect result. "
                "Identify the bug. Note: the error is scientific, "
                "not syntactic."
            ),
            (
                "Write a reproducible analysis script for the "
                "following experiment. Include: random seed setting, "
                "parameter logging, intermediate result checkpointing, "
                "and a README describing how to reproduce the output."
            ),
            (
                "Write unit tests for the following scientific "
                "function where the ground truth is known analytically. "
                "Include edge cases specific to the scientific domain."
            ),
        ]
        examples = []
        for i in range(count):
            topic = topics[i % len(topics)]
            suffix = question_type_suffixes[i % len(question_type_suffixes)]
            base = self.teacher.teachers[0].generate_training_example(
                topic, difficulty=0.90, num_answers=5
            )
            examples.append(TrainingExample(
                question=(
                    f"[Research Computing Task]\n"
                    f"Scientific context: {topic}\n"
                    f"Problem: {base.question}\n\n"
                    f"{suffix}"
                ),
                answers=base.answers,
                correct_indices=base.correct_indices,
                difficulty=0.90,
                domain=f"research_computing_{base.domain}",
                explanation=(
                    f"Research computing and scientific coding: "
                    f"{base.explanation}"
                ),
            ))
        return examples

    def _gen_adversarial_robustness(
        self, count: int
    ) -> List[TrainingExample]:
        """
        Phase 11: Adversarial Robustness & Epistemic Integrity.
        Generates prompts with plausible but flawed scientific
        content. Model must detect flaws, resist confident
        misinformation, and maintain appropriate uncertainty.
        Teacher-student loop enforces correctness >= 0.91.
        """
        topics = self._get_topics()
        question_type_suffixes = [
            (
                "The following abstract is presented with high "
                "confidence. Identify all methodological flaws. "
                "State what the data actually supports vs. what "
                "the authors claim. Do not assume the finding is "
                "correct before evaluating it."
            ),
            (
                "Examine the following reported results for "
                "data fabrication indicators: too-clean results, "
                "impossible standard deviations, suspicious digit "
                "patterns, or implausible effect sizes. "
                "Justify each flag."
            ),
            (
                "The following paper structure is described. "
                "Determine whether the authors are HARKing "
                "(Hypothesising After Results are Known). "
                "Identify the specific indicators."
            ),
            (
                "A researcher asks you to accept the following "
                "premise as established and build on it. "
                "Evaluate the premise first. If it is not "
                "sufficiently supported, state what would be "
                "needed before it could be accepted."
            ),
            (
                "The following argument uses rhetorical rather than "
                "evidential reasoning to support a scientific claim. "
                "Identify each rhetorical move and explain why it "
                "does not constitute scientific evidence."
            ),
            (
                "You are presented with a confident claim and asked "
                "to agree. The claim has a plausible mechanism but "
                "insufficient evidence. Maintain appropriate "
                "uncertainty and explain exactly what evidence "
                "threshold would warrant confidence."
            ),
        ]
        examples = []
        for i in range(count):
            topic = topics[i % len(topics)]
            suffix = question_type_suffixes[i % len(question_type_suffixes)]
            base = self.teacher.teachers[0].generate_training_example(
                topic, difficulty=0.95, num_answers=5
            )
            examples.append(TrainingExample(
                question=(
                    f"[Adversarial Robustness Task]\n"
                    f"Domain: {topic}\n"
                    f"Content to evaluate: {base.question}\n\n"
                    f"{suffix}"
                ),
                answers=base.answers,
                correct_indices=base.correct_indices,
                difficulty=0.97,
                domain=f"adversarial_robustness_{base.domain}",
                explanation=(
                    f"Adversarial robustness and epistemic integrity: "
                    f"{base.explanation}"
                ),
            ))
        return examples

    def _gen_synthetic_judgment(
        self, count: int
    ) -> List[TrainingExample]:
        """
        Phase 12: Synthetic Judgment.
        Generates integrated decision-under-uncertainty prompts
        drawing on all prior phases. Feeds Phase12Trainer PPO loop.
        """
        topics = self._get_topics()
        question_type_suffixes = [
            (
                "Make a decision on the following scientific question "
                "under uncertainty. Show stepwise causal reasoning, "
                "state your confidence explicitly, identify what "
                "information would change your decision, and abstain "
                "if the evidence is insufficient to decide."
            ),
            (
                "You previously held the following belief based on "
                "early evidence. New evidence is now presented. "
                "Revise your belief explicitly, quantify the update, "
                "and state whether the new evidence is sufficient "
                "to overturn the prior."
            ),
            (
                "The following scientific scenario contains a hidden "
                "confounder. Identify it, explain how it affects "
                "causal interpretation, and state what experiment "
                "would isolate the true causal effect."
            ),
        ]
        examples = []
        for i in range(count):
            topic = topics[i % len(topics)]
            suffix = question_type_suffixes[i % len(question_type_suffixes)]
            base = self.teacher.teachers[0].generate_training_example(
                topic, difficulty=0.98, num_answers=5
            )
            examples.append(TrainingExample(
                question=(
                    f"[Synthetic Judgment Task]\n"
                    f"Domain: {topic}\n"
                    f"Scenario: {base.question}\n\n"
                    f"{suffix}"
                ),
                answers=base.answers,
                correct_indices=base.correct_indices,
                difficulty=0.98,
                domain=f"synthetic_judgment_{base.domain}",
                explanation=(
                    f"Synthetic judgment under uncertainty: "
                    f"{base.explanation}"
                ),
            ))
        return examples

    @property
    def phase6_loop(self) -> Phase7TeacherStudentLoop:
        """Access Phase 6 (Niche Scientific) teacher-student loop."""
        return self._phase6_loop

    @property
    def phase11_loop(self) -> Phase7TeacherStudentLoop:
        """Access Phase 11 (Adversarial Robustness) teacher-student loop."""
        return self._phase11_loop


# ─── Phase Completion Monitor ─────────────────────────────────────────────────

class PhaseCompletionMonitor:
    """
    Objective, data-driven phase completion monitor.

    Combines two signals to determine when a curriculum phase is complete:
      1. Prompt coverage ratio  — breadth: what fraction of phase prompts
                                  have received valid student answers.
      2. Semantic saturation    — depth: are student outputs becoming
                                  semantically redundant (high similarity
                                  to recent outputs = knowledge plateau).

    Both signals must exceed their configured thresholds simultaneously
    before a phase is declared complete.

    This runs alongside the existing validation-loss plateau detection
    in the training loop (server.py). Phase advancement requires EITHER:
      - Plateau detection triggers (val_loss stagnant for N checks), OR
      - PhaseCompletionMonitor declares complete (coverage + saturation).
    Whichever occurs first advances the phase.

    Usage:
        monitor = PhaseCompletionMonitor(phase_config, phase_prompts)
        # After each student answer:
        monitor.update(answer_text, answer_embedding)
        if monitor.is_complete():
            curriculum.advance_phase()
        metrics = monitor.get_metrics()
    """

    def __init__(
        self,
        phase_config: PhaseConfig,
        phase_prompts: List[Dict],
        thresholds: Optional[Dict] = None,
    ):
        """
        Args:
            phase_config:   PhaseConfig for the current phase.
            phase_prompts:  List of prompt dicts, each must contain
                            a unique 'id' field.
                            e.g. [{'id': 'p1', 'text': '...'}, ...]
            thresholds:     Override default thresholds. Keys:
                            'coverage_ratio', 'saturation_score',
                            'max_iterations'.
        """
        self._phase_config = phase_config
        self._phase_prompts = phase_prompts
        self._total_prompts = max(len(phase_prompts), 1)

        # Merge thresholds: phase_config.completion_criteria
        # → config.yaml phase_monitor → caller override
        from logiik.config import CONFIG
        cfg_thresholds = CONFIG.get("phase_monitor", {})
        phase_thresholds = phase_config.completion_criteria or {}

        self._thresholds = {
            "coverage_ratio": phase_thresholds.get(
                "coverage_ratio",
                cfg_thresholds.get("coverage_ratio", 0.95)
            ),
            "saturation_score": phase_thresholds.get(
                "saturation_score",
                cfg_thresholds.get("saturation_score", 0.90)
            ),
            "max_iterations": phase_thresholds.get(
                "max_iterations",
                cfg_thresholds.get("max_iterations", 1000)
            ),
        }
        if thresholds:
            self._thresholds.update(thresholds)

        # State
        self._covered_prompts: set = set()
        self._recent_embeddings: List[np.ndarray] = []
        self._past_embeddings: List[np.ndarray] = []
        self._iteration: int = 0
        self._metrics_log: List[Dict] = []

        logger.info(
            f"PhaseCompletionMonitor initialised: "
            f"phase={phase_config.display_name}, "
            f"total_prompts={self._total_prompts}, "
            f"thresholds={self._thresholds}"
        )

    # ─── Public API ───────────────────────────────────────────────────────

    def update(
        self,
        answer_text: str,
        answer_embedding: np.ndarray,
        prompt_id: Optional[str] = None,
    ) -> Dict:
        """
        Process one student answer.

        Call this after every student output during training.

        Args:
            answer_text:      Raw string output from student model.
            answer_embedding: SPECTER2 embedding of answer_text,
                              shape (768,).
            prompt_id:        ID of the prompt this answer responds to.
                              If None, coverage tracking is skipped for
                              this answer (saturation still tracked).

        Returns:
            Dict with current coverage_ratio, saturation_score,
            iteration, and is_complete flag.
        """
        self._iteration += 1

        # Update prompt coverage
        if prompt_id and validate_answer(answer_text):
            self._covered_prompts.add(prompt_id)

        # Update embedding history
        self._recent_embeddings.append(answer_embedding)
        self._past_embeddings.append(answer_embedding)

        # Keep recent window bounded (last 50 for saturation check)
        if len(self._recent_embeddings) > 50:
            self._recent_embeddings.pop(0)

        # Compute metrics
        coverage = self._compute_coverage()
        saturation = self._compute_saturation(answer_embedding)

        metrics = {
            "iteration": self._iteration,
            "phase": self._phase_config.display_name,
            "coverage_ratio": round(coverage, 4),
            "saturation_score": round(saturation, 4),
            "covered_prompts": len(self._covered_prompts),
            "total_prompts": self._total_prompts,
            "is_complete": self._check_complete(coverage, saturation),
        }
        self._metrics_log.append(metrics)

        log_event(
            "core.training",
            f"[PhaseMonitor] phase={self._phase_config.display_name} | "
            f"iter={self._iteration} | "
            f"coverage={coverage:.3f} | "
            f"saturation={saturation:.3f} | "
            f"complete={metrics['is_complete']}",
            level="debug"
        )
        return metrics

    def is_complete(self) -> bool:
        """
        Returns True if both coverage and saturation thresholds
        are met, or max_iterations is reached.
        """
        if self._iteration >= self._thresholds["max_iterations"]:
            logger.warning(
                f"Phase {self._phase_config.display_name} reached "
                f"max_iterations={self._thresholds['max_iterations']} "
                "without meeting thresholds. Forcing advancement."
            )
            return True
        coverage = self._compute_coverage()
        saturation = self._compute_saturation(
            self._past_embeddings[-1]
            if self._past_embeddings
            else np.zeros(768)
        )
        return self._check_complete(coverage, saturation)

    def get_metrics(self) -> Dict:
        """
        Return current phase completion metrics snapshot.
        Safe to call at any time.
        """
        coverage = self._compute_coverage()
        saturation = (
            self._compute_saturation(self._past_embeddings[-1])
            if self._past_embeddings
            else 0.0
        )
        return {
            "phase": self._phase_config.display_name,
            "phase_id": self._phase_config.id,
            "iteration": self._iteration,
            "coverage_ratio": round(coverage, 4),
            "coverage_target": self._thresholds["coverage_ratio"],
            "saturation_score": round(saturation, 4),
            "saturation_target": self._thresholds["saturation_score"],
            "covered_prompts": len(self._covered_prompts),
            "total_prompts": self._total_prompts,
            "is_complete": self.is_complete(),
            "thresholds": self._thresholds,
        }

    def get_metrics_log(self) -> List[Dict]:
        """Return full per-iteration metrics history."""
        return self._metrics_log

    def reset(self, phase_config: PhaseConfig, phase_prompts: List[Dict]):
        """
        Reset monitor for a new phase.
        Call immediately after phase advancement.
        """
        self._phase_config = phase_config
        self._phase_prompts = phase_prompts
        self._total_prompts = max(len(phase_prompts), 1)
        self._covered_prompts = set()
        self._recent_embeddings = []
        self._past_embeddings = []
        self._iteration = 0
        self._metrics_log = []
        logger.info(
            f"PhaseCompletionMonitor reset for phase: "
            f"{phase_config.display_name}"
        )

    # ─── Internal computation ─────────────────────────────────────────────

    def _compute_coverage(self) -> float:
        """Coverage ratio: fraction of prompts with valid answers."""
        return len(self._covered_prompts) / self._total_prompts

    def _compute_saturation(self, new_embedding: np.ndarray) -> float:
        """
        Semantic saturation: average similarity of new_embedding
        to last top_k embeddings in history.
        Delegates to canonical compute_saturation in utils/helpers.py.
        """
        if len(self._past_embeddings) < 2:
            return 0.0
        # Exclude the embedding just appended (itself)
        history = self._past_embeddings[:-1]
        return compute_saturation(new_embedding, history, top_k=5)

    def _check_complete(self, coverage: float, saturation: float) -> bool:
        """Returns True if both thresholds simultaneously met."""
        return (
            coverage >= self._thresholds["coverage_ratio"]
            and saturation >= self._thresholds["saturation_score"]
        )


# ─── Training loop integration helper ────────────────────────────────────────

def build_phase_monitor(
    phase_id: int,
    phase_prompts: Optional[List[Dict]] = None,
    thresholds: Optional[Dict] = None,
) -> PhaseCompletionMonitor:
    """
    Convenience factory: build a PhaseCompletionMonitor for a given
    phase ID.

    Args:
        phase_id:      1-indexed phase ID (matches PHASES list).
        phase_prompts: List of prompt dicts with 'id' field.
                       Pass empty list if prompts not yet available —
                       coverage tracking will be disabled but saturation
                       still works.
        thresholds:    Optional threshold overrides.

    Returns:
        PhaseCompletionMonitor ready for use in training loop.

    Usage in training loop:
        monitor = build_phase_monitor(7, phase_prompts)
        for answer in student_outputs:
            emb = embedder.embed_text(answer.text)
            metrics = monitor.update(answer.text, emb, answer.prompt_id)
            log_event("training", str(metrics))
            if monitor.is_complete():
                curriculum.advance_phase()
                monitor.reset(
                    get_phase(curriculum.current_phase + 1),
                    next_phase_prompts
                )
    """
    phase_config = get_phase(phase_id)
    if phase_config is None:
        raise ValueError(f"Unknown phase_id={phase_id}")
    prompts = phase_prompts or []
    return PhaseCompletionMonitor(phase_config, prompts, thresholds)
