"""
Logiik Core Training Module.

Implements the Phase 7 teacher-student loop with iterative feedback
and the GenerativeCurriculum adapted from cognita/training/curriculum.py.

Key changes from legacy NERO/Cognita:
  - Phase 7 renamed from "Drosophila AI Framework" to
    "Niche Scientific Reasoning" with new question types.
  - Phase completion now combines plateau detection (existing)
    with coverage ratio + semantic saturation (new — CHUNK-08).
  - All logging routes through logiik/utils/logging.py.
  - All imports use logiik.* namespace.

Legacy reference:
  cognita/core/brain.py         → NEROBrain (unchanged, still used)
  cognita/training/curriculum.py → GenerativeCurriculum (migrated here)
"""
import uuid
import asyncio
import json
import math
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass

import torch
import numpy as np
from torch.optim import AdamW
from torch.optim.lr_scheduler import LinearLR
from torch.utils.data import DataLoader, Dataset

from logiik.curriculum.phases import PHASES, get_phase, PhaseConfig
from logiik.storage.text_store import TextStore
from logiik.embeddings.embed import get_embedder
from logiik.utils.logging import get_logger
from logiik.utils.helpers import validate_answer, compute_saturation

logger = get_logger("core.training")


# ─── Phase 7 data structures ──────────────────────────────────────────────────

@dataclass
class TeacherQuestion:
    """
    A single Phase 7 teacher-generated question with stepwise reasoning.
    Stored in Firebase via TextStore.
    """
    question_id: str
    prompt: str
    answer_steps: List[str]
    full_answer: str
    phase_id: int = 7
    difficulty: float = 0.94


@dataclass
class StudentAttempt:
    """
    A single student attempt at a Phase 7 question.
    May be updated through multiple feedback iterations.
    """
    question_id: str
    attempt_index: int
    student_answer_steps: List[str]
    student_full_answer: str
    feedback: Optional[List[str]] = None
    correctness: Optional[float] = None
    suggested_improvement: Optional[str] = None


# ─── Phase 7 Teacher-Student Loop ────────────────────────────────────────────

class Phase7TeacherStudentLoop:
    """
    Iterative teacher-student training loop for Phase 7:
    Niche Scientific Reasoning.

    Workflow per question:
      1. Teacher generates question + stepwise reasoning.
      2. Student generates stepwise answer + full answer.
      3. Teacher evaluates: assigns correctness score + feedback.
      4. If correctness < threshold (0.90): student regenerates.
      5. Loop until correctness >= 0.90 or max_iterations reached.
      6. Store final QA pair in Firebase + Pinecone.

    All questions and attempts persisted to Firebase via TextStore.
    """

    CORRECTNESS_THRESHOLD = 0.90
    MAX_ITERATIONS = 10    # Max feedback loops per question

    def __init__(self, text_store: Optional[TextStore] = None):
        self._store = text_store or TextStore()
        # In-memory stores (mirrored to Firebase)
        self._teacher_db: Dict[str, TeacherQuestion] = {}
        self._student_db: Dict[str, List[StudentAttempt]] = {}
        self._metrics: Dict[str, Dict] = {}
        logger.info("Phase7TeacherStudentLoop initialised.")

    def generate_teacher_question(
        self,
        prompt: str,
        answer_steps: List[str],
        full_answer: str,
        difficulty: float = 0.94
    ) -> str:
        """
        Register a teacher-generated question.

        In production, prompt + answer_steps are generated by the
        teacher model (GPT-4 / Claude API call). This method stores
        the result and returns the question_id.

        Args:
            prompt:       The scientific question/scenario.
            answer_steps: List of stepwise reasoning strings.
            full_answer:  Complete natural language answer.
            difficulty:   Difficulty score (0–1).

        Returns:
            question_id: UUID string.
        """
        qid = str(uuid.uuid4())
        question = TeacherQuestion(
            question_id=qid,
            prompt=prompt,
            answer_steps=answer_steps,
            full_answer=full_answer,
            difficulty=difficulty,
        )
        self._teacher_db[qid] = question
        self._student_db[qid] = []

        # Persist to Firebase
        self._store.store_phase7_teacher(qid, {
            "prompt": prompt,
            "answer_steps": answer_steps,
            "full_answer": full_answer,
            "difficulty": difficulty,
            "phase_id": 7,
        })

        logger.debug(f"Teacher question registered: id={qid}")
        return qid

    def student_attempt(
        self,
        question_id: str,
        student_answer_steps: List[str],
        student_full_answer: str
    ) -> StudentAttempt:
        """
        Record a student attempt at a Phase 7 question.

        Args:
            question_id:          ID from generate_teacher_question.
            student_answer_steps: Student's stepwise reasoning.
            student_full_answer:  Student's complete answer.

        Returns:
            StudentAttempt object (correctness not yet assigned).
        """
        if question_id not in self._student_db:
            self._student_db[question_id] = []

        attempt_index = len(self._student_db[question_id])
        attempt = StudentAttempt(
            question_id=question_id,
            attempt_index=attempt_index,
            student_answer_steps=student_answer_steps,
            student_full_answer=student_full_answer,
        )
        self._student_db[question_id].append(attempt)

        logger.debug(
            f"Student attempt recorded: "
            f"question_id={question_id}, attempt={attempt_index}"
        )
        return attempt

    def provide_feedback(
        self,
        question_id: str,
        attempt_index: int,
        feedback: List[str],
        correctness: float,
        suggested_improvement: Optional[str] = None
    ) -> bool:
        """
        Apply teacher feedback to a student attempt.

        Args:
            question_id:            Target question ID.
            attempt_index:          Index of the attempt to update.
            feedback:               List of feedback strings per step.
            correctness:            Score 0–1 (threshold: 0.90).
            suggested_improvement:  Optional specific improvement hint.

        Returns:
            True if correctness threshold met (phase 7 QA accepted).
            False if student should regenerate.
        """
        if question_id not in self._student_db:
            logger.error(f"provide_feedback: unknown question_id={question_id}")
            return False

        attempts = self._student_db[question_id]
        if attempt_index >= len(attempts):
            logger.error(
                f"provide_feedback: attempt_index={attempt_index} "
                f"out of range for question_id={question_id}"
            )
            return False

        attempt = attempts[attempt_index]
        attempt.feedback = feedback
        attempt.correctness = correctness
        attempt.suggested_improvement = suggested_improvement

        # Persist feedback to Firebase
        self._store.store_phase7_student(
            f"{question_id}_attempt_{attempt_index}",
            {
                "question_id": question_id,
                "attempt_index": attempt_index,
                "student_answer_steps": attempt.student_answer_steps,
                "student_full_answer": attempt.student_full_answer,
                "feedback": feedback,
                "correctness": correctness,
                "suggested_improvement": suggested_improvement or "",
            }
        )

        threshold_met = correctness >= self.CORRECTNESS_THRESHOLD
        status = "ACCEPTED" if threshold_met else "NEEDS_REVISION"
        logger.info(
            f"Feedback applied: question_id={question_id}, "
            f"attempt={attempt_index}, correctness={correctness:.2f}, "
            f"status={status}"
        )
        return threshold_met

    def run_feedback_loop(
        self,
        question_id: str,
        student_fn,
        teacher_fn
    ) -> Tuple[bool, int, float]:
        """
        Run the full iterative feedback loop for one question.

        Args:
            question_id: Target question ID.
            student_fn:  Callable(prompt, steps, suggestion) ->
                         (answer_steps: List[str], full_answer: str)
            teacher_fn:  Callable(prompt, teacher_steps,
                         student_steps, student_answer) ->
                         (feedback: List[str], correctness: float,
                          suggestion: str)

        Returns:
            Tuple of (threshold_met: bool, iterations: int,
                      final_correctness: float)
        """
        if question_id not in self._teacher_db:
            logger.error(
                f"run_feedback_loop: unknown question_id={question_id}"
            )
            return False, 0, 0.0

        question = self._teacher_db[question_id]
        threshold_met = False
        final_correctness = 0.0
        suggestion = None

        for iteration in range(self.MAX_ITERATIONS):
            # Student generates answer
            student_steps, student_answer = student_fn(
                question.prompt,
                question.answer_steps,
                suggestion
            )

            # Validate minimum answer quality
            if not validate_answer(student_answer):
                logger.warning(
                    f"Student answer failed validation at iteration "
                    f"{iteration} for question_id={question_id}"
                )
                continue

            # Record attempt
            self.student_attempt(question_id, student_steps, student_answer)

            # Teacher evaluates
            feedback, correctness, suggestion = teacher_fn(
                question.prompt,
                question.answer_steps,
                student_steps,
                student_answer
            )

            # Apply feedback
            threshold_met = self.provide_feedback(
                question_id,
                iteration,
                feedback,
                correctness,
                suggestion
            )
            final_correctness = correctness

            if threshold_met:
                logger.info(
                    f"Phase 7 question accepted after {iteration + 1} "
                    f"iterations: correctness={correctness:.2f}"
                )
                break
            else:
                logger.debug(
                    f"Iteration {iteration + 1}: correctness={correctness:.2f} "
                    f"< {self.CORRECTNESS_THRESHOLD} — regenerating."
                )

        if not threshold_met:
            logger.warning(
                f"Phase 7 question {question_id} did not meet threshold "
                f"after {self.MAX_ITERATIONS} iterations. "
                f"Final correctness={final_correctness:.2f}"
            )

        # Record metrics
        self._metrics[question_id] = {
            "iterations": min(self.MAX_ITERATIONS, iteration + 1),
            "final_correctness": final_correctness,
            "threshold_met": threshold_met,
        }

        return threshold_met, iteration + 1, final_correctness

    def get_metrics(self) -> Dict:
        """Return aggregate Phase 7 loop metrics."""
        if not self._metrics:
            return {"total_questions": 0}
        total = len(self._metrics)
        accepted = sum(1 for m in self._metrics.values() if m["threshold_met"])
        avg_iter = np.mean([m["iterations"] for m in self._metrics.values()])
        avg_corr = np.mean(
            [m["final_correctness"] for m in self._metrics.values()]
        )
        return {
            "total_questions": total,
            "accepted": accepted,
            "acceptance_rate": accepted / total,
            "avg_iterations": float(avg_iter),
            "avg_final_correctness": float(avg_corr),
        }


# ─── Processed example for DataLoader ────────────────────────────────────────

@dataclass
class ProcessedExample:
    """Tokenized training example for DataLoader."""
    input_ids: torch.Tensor
    attention_mask: torch.Tensor
    labels: torch.Tensor
    teacher_logits: Optional[torch.Tensor]
    weight: float


def collate_examples(batch: List[ProcessedExample]) -> ProcessedExample:
    """
    Custom collate — stacks fixed-size tensors.
    Drops variable-length teacher_logits to avoid shape mismatch.
    Preserved from legacy cognita/training/curriculum.py.
    """
    return ProcessedExample(
        input_ids=torch.stack([b.input_ids for b in batch]),
        attention_mask=torch.stack([b.attention_mask for b in batch]),
        labels=torch.stack([b.labels for b in batch]),
        teacher_logits=None,
        weight=sum(b.weight for b in batch) / len(batch),
    )


# ─── Training example type ────────────────────────────────────────────────────

@dataclass
class TrainingExample:
    """
    Single training example in Logiik Q+A format.
    Migrated from cognita/core/teacher_interface.py TrainingExample.
    """
    question: str
    answers: List[str]
    correct_indices: List[int]
    difficulty: float
    domain: str
    explanation: str


# ─── Curriculum Dataset ───────────────────────────────────────────────────────

class CurriculumDataset(Dataset):
    """
    Dataset implementing the Q+A training structure.
    Migrated and renamed from legacy CurriculumDataset.
    Preserves all logic including train/val split and
    soft teacher logit simulation.
    """

    def __init__(
        self,
        examples: List[TrainingExample],
        tokenizer,
        max_length: int = 512,
        generative_ratio: float = 0.3,
        val_ratio: float = 0.1,
        _items=None,
    ):
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.generative_ratio = generative_ratio

        if _items is not None:
            self.items = _items
            self.examples = examples
            self._val_dataset = None
            return

        all_items = [
            (ex, ans_idx)
            for ex in examples
            for ans_idx in range(len(ex.answers))
        ]
        split = int(len(all_items) * (1 - val_ratio))
        self.items = all_items[:split]
        val_items = all_items[split:]
        self._val_dataset = CurriculumDataset(
            examples, tokenizer, max_length,
            generative_ratio, _items=val_items
        )
        self.examples = examples

    @property
    def val_dataset(self):
        return self._val_dataset

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx) -> ProcessedExample:
        example, ans_idx = self.items[idx]
        question_prefix = f"Question: {example.question}\nAnswer:"
        formatted_text = (
            f"Question: {example.question}\n"
            f"Answer: {example.answers[ans_idx]}"
        )
        encoding = self.tokenizer(
            formatted_text,
            max_length=self.max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt"
        )
        prefix_ids = self.tokenizer(
            question_prefix,
            add_special_tokens=False,
            return_tensors="pt"
        )["input_ids"]
        prefix_len = prefix_ids.shape[1]
        labels = encoding["input_ids"].clone()
        labels[labels == self.tokenizer.pad_token_id] = -100
        labels[:, :prefix_len] = -100

        teacher_logits = self._simulate_teacher_logits(example, ans_idx)
        weight = 1.0 + example.difficulty

        return ProcessedExample(
            input_ids=encoding["input_ids"].squeeze(0),
            attention_mask=encoding["attention_mask"].squeeze(0),
            labels=labels.squeeze(0),
            teacher_logits=teacher_logits,
            weight=weight
        )

    def _simulate_teacher_logits(
        self, example: TrainingExample, ans_idx: int
    ) -> torch.Tensor:
        vocab_size = self.tokenizer.vocab_size
        answer_tokens = self.tokenizer.encode(
            example.answers[ans_idx], add_special_tokens=False
        )
        seq_len = len(answer_tokens)
        logits = torch.zeros(seq_len, vocab_size)
        for pos, token_id in enumerate(answer_tokens):
            if token_id < vocab_size:
                logits[pos, token_id] = 2.0
        return logits


# ─── Generative Curriculum ────────────────────────────────────────────────────

class GenerativeCurriculum:
    """
    Logiik curriculum engine.
    Migrated from cognita/training/curriculum.py GenerativeCurriculum.

    Phase 7 updated: "Drosophila AI Framework" replaced with
    "Niche Scientific Reasoning" (teacher_student=True,
    correctness_threshold=0.90).

    Phase advancement uses plateau detection from server.py
    (val_loss plateau) combined with coverage + saturation
    metrics added in CHUNK-08.
    """

    def __init__(
        self,
        teacher_orchestrator,
        tokenizer,
        topics_description: str = "",
        phase_ratios: Tuple[float, ...] = (
            0.20, 0.20, 0.15, 0.15, 0.12, 0.10, 0.08
        ),
        phase_topics: Optional[Dict[str, List[str]]] = None,
        topics_per_session: int = 5,
    ):
        self.teacher = teacher_orchestrator
        self.tokenizer = tokenizer
        self.topics_description = topics_description
        self.topics_per_session = topics_per_session
        self.current_phase = 0   # 0-indexed internally

        # Phase names from canonical PHASES list
        self.phase_names = [p.display_name for p in PHASES]
        self.phase_configs = {p.display_name: p for p in PHASES}

        self.phase_ratios = self._normalize_ratios(phase_ratios)
        self.phase_topics: Dict[str, List[str]] = phase_topics or {}
        self._topic_cursors: Dict[str, int] = {
            name.lower(): 0 for name in self.phase_names
        }

        # Phase 7 teacher-student loop instance
        self._phase7_loop = Phase7TeacherStudentLoop()

        logger.info(
            f"GenerativeCurriculum initialised: "
            f"{len(self.phase_names)} phases"
        )

    def _normalize_ratios(
        self, ratios: Tuple[float, ...]
    ) -> Tuple[float, ...]:
        n = len(self.phase_names)
        if not ratios:
            return tuple(0.3 for _ in range(n))
        if len(ratios) < n:
            pad = ratios[-1]
            return tuple(ratios) + tuple(pad for _ in range(n - len(ratios)))
        return tuple(ratios[:n])

    def _get_topics(self) -> List[str]:
        phase_key = self.phase_names[self.current_phase].lower()
        topics = self.phase_topics.get(phase_key, [])
        if not topics:
            return (
                [self.topics_description]
                if self.topics_description.strip()
                else ["general_knowledge"]
            )
        n = len(topics)
        start = self._topic_cursors[phase_key]
        selected = [
            topics[(start + i) % n]
            for i in range(self.topics_per_session)
        ]
        self._topic_cursors[phase_key] = (
            (start + self.topics_per_session) % n
        )
        return selected

    def generate_phase_batch(
        self,
        batch_size: int,
        question_bank=None,
    ) -> CurriculumDataset:
        """Generate training batch for current phase."""
        phase_name = self.phase_names[self.current_phase]
        phase_config = self.phase_configs[phase_name]

        logger.info(
            f"Generating batch: phase={phase_name}, "
            f"batch_size={batch_size}"
        )

        # Route to phase-specific generator
        if self.current_phase == 0:
            examples = self._gen_memorization(batch_size)
        elif self.current_phase == 1:
            examples = self._gen_generation(batch_size)
        elif self.current_phase == 2:
            examples = self._gen_abstraction(batch_size)
        elif self.current_phase == 3:
            examples = self._gen_engineering(batch_size)
        elif self.current_phase == 4:
            examples = self._gen_coding(batch_size)
        elif self.current_phase == 5:
            examples = self._gen_scientific_reasoning(batch_size)
        elif self.current_phase == 6:
            # Phase 7 (0-indexed: 6) — Niche Scientific Reasoning
            examples = self._gen_niche_scientific(batch_size)
        else:
            examples = self._gen_memorization(batch_size)

        # Deduplication via question bank
        if question_bank and examples:
            filtered = [
                ex for ex in examples
                if question_bank.check_and_log(
                    ex.question, self.topics_description
                )
            ]
            examples = filtered if filtered else examples[:1]

        return CurriculumDataset(
            examples,
            self.tokenizer,
            generative_ratio=self.phase_ratios[self.current_phase]
        )

    def advance_phase(self) -> bool:
        """Advance to next phase. Returns False if already at last phase."""
        if self.current_phase < len(self.phase_names) - 1:
            self.current_phase += 1
            logger.info(
                f"Advanced to phase {self.current_phase + 1}: "
                f"{self.phase_names[self.current_phase]}"
            )
            return True
        logger.info("All phases complete.")
        return False

    # ─── Phase generators ─────────────────────────────────────────────────

    def _make_example(
        self,
        topic: str,
        prefix: str,
        suffix: str,
        difficulty: float,
        domain_prefix: str,
    ) -> TrainingExample:
        """Helper: generate one example via teacher, apply prefix/suffix."""
        base = self.teacher.teachers[0].generate_training_example(
            topic, difficulty=difficulty, num_answers=5
        )
        return TrainingExample(
            question=f"{prefix}{base.question}\n{suffix}",
            answers=base.answers,
            correct_indices=base.correct_indices,
            difficulty=difficulty,
            domain=f"{domain_prefix}_{base.domain}",
            explanation=base.explanation,
        )

    def _gen_memorization(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        return self.teacher.generate_curriculum_batch(
            topics,
            examples_per_topic=max(1, count // len(topics)),
            difficulty_progression=True
        )

    def _gen_generation(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        examples = []
        for topic in topics:
            base = self.teacher.teachers[0].generate_training_example(
                topic, num_answers=3
            )
            examples.append(TrainingExample(
                question=(
                    base.question +
                    "\n(Provide an original answer based on "
                    "your understanding)"
                ),
                answers=["[GENERATE]"],
                correct_indices=[0],
                difficulty=min(base.difficulty * 1.2, 1.0),
                domain=base.domain,
                explanation="Generate original answer showing understanding",
            ))
        return examples[:count]

    def _gen_abstraction(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        return [
            self._make_example(
                topics[i % len(topics)],
                prefix="Connecting ideas across fields: ",
                suffix="(Draw on knowledge from multiple domains)",
                difficulty=0.90,
                domain_prefix="cross_domain",
            )
            for i in range(count)
        ]

    def _gen_engineering(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        return [
            self._make_example(
                topics[i % len(topics)],
                prefix="Engineering execution scenario: ",
                suffix=(
                    "(Plan implementation, propose tests, debug likely "
                    "failure modes, and justify trade-offs in "
                    "reliability/security/performance)"
                ),
                difficulty=0.92,
                domain_prefix="engineering_execution",
            )
            for i in range(count)
        ]

    def _gen_coding(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        return [
            self._make_example(
                topics[i % len(topics)],
                prefix="Coding mastery challenge: ",
                suffix=(
                    "(Demonstrate robust implementation choices across "
                    "common programming languages)"
                ),
                difficulty=0.95,
                domain_prefix="coding_mastery",
            )
            for i in range(count)
        ]

    def _gen_scientific_reasoning(self, count: int) -> List[TrainingExample]:
        topics = self._get_topics()
        return [
            self._make_example(
                topics[i % len(topics)],
                prefix="Scientific reasoning challenge: ",
                suffix=(
                    "(State hypotheses, define controls, identify "
                    "confounders, and provide uncertainty-aware conclusions)"
                ),
                difficulty=0.96,
                domain_prefix="scientific_reasoning",
            )
            for i in range(count)
        ]

    def _gen_niche_scientific(self, count: int) -> List[TrainingExample]:
        """
        Phase 7: Niche Scientific Reasoning.
        Generates interdisciplinary, mechanistic, and hypothetical
        scientific prompts requiring stepwise reasoning.

        NOTE: In full Phase 7 operation, these examples feed into
        Phase7TeacherStudentLoop.run_feedback_loop() for iterative
        correctness enforcement. The CurriculumDataset returned here
        is used for the base training pass; the feedback loop runs
        as a separate process via the API.
        """
        topics = self._get_topics()
        question_types = [
            "hypothetical_scenario",
            "multi_step_experimental_design",
            "interdisciplinary_synthesis",
            "mechanistic_reasoning",
            "rare_data_interpretation",
        ]
        examples = []
        for i in range(count):
            topic = topics[i % len(topics)]
            q_type = question_types[i % len(question_types)]
            base = self.teacher.teachers[0].generate_training_example(
                topic, difficulty=0.95, num_answers=5
            )
            examples.append(TrainingExample(
                question=(
                    f"[{q_type.replace('_', ' ').title()}] "
                    f"{base.question}\n"
                    "(Provide stepwise reasoning: identify mechanism, "
                    "predict outcome, explain experimental evidence, "
                    "address edge cases and interdisciplinary connections.)"
                ),
                answers=base.answers,
                correct_indices=base.correct_indices,
                difficulty=0.98,
                domain=f"niche_scientific_{base.domain}",
                explanation=(
                    f"Niche scientific reasoning [{q_type}]: "
                    f"{base.explanation}"
                ),
            ))
        return examples

    @property
    def phase7_loop(self) -> Phase7TeacherStudentLoop:
        """Access Phase 7 teacher-student loop directly."""
        return self._phase7_loop
